# Generated by Django 4.1.2 on 2022-11-30 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0003_rename_dialysis_taget_max_nutrient_dialysis_target_max'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='diagnosis_date',
        ),
    ]
