# Generated by Django 4.1.2 on 2022-11-30 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0004_remove_patient_diagnosis_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report_serum',
            old_name='Abumin',
            new_name='abumin',
        ),
        migrations.AlterField(
            model_name='patient_login',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='client_app.user'),
        ),
    ]
