# Generated by Django 4.1.2 on 2022-12-01 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0005_rename_abumin_report_serum_abumin_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='SiteUser',
        ),
        migrations.RenameField(
            model_name='patient_login',
            old_name='username',
            new_name='SiteUsername',
        ),
        migrations.RenameField(
            model_name='sponsor_login',
            old_name='username',
            new_name='SiteUsername',
        ),
        migrations.AlterModelTable(
            name='siteuser',
            table='SiteUser',
        ),
    ]
