# Generated by Django 4.1.2 on 2022-12-01 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0006_rename_user_siteuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsor_login',
            name='sponsor',
        ),
        migrations.DeleteModel(
            name='Patient_Login',
        ),
        migrations.DeleteModel(
            name='Sponsor_Login',
        ),
    ]
