# Generated by Django 4.1.2 on 2022-12-01 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0007_remove_sponsor_login_sponsor_delete_patient_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='username',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='siteuser',
            name='username',
            field=models.CharField(default='', max_length=150),
        ),
    ]
