# Generated by Django 4.1.2 on 2022-12-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0008_patient_username_siteuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='report_drink',
            name='username',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='report_food',
            name='username',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='report_serum',
            name='username',
            field=models.CharField(default='', max_length=150),
        ),
    ]
