# Generated by Django 4.1.2 on 2022-12-01 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0009_report_drink_username_report_food_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fluid_type',
            name='units',
        ),
        migrations.RemoveField(
            model_name='food_type',
            name='units',
        ),
    ]
