# Generated by Django 4.1.2 on 2022-12-01 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0010_remove_fluid_type_units_remove_food_type_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fluid_type',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='food_item',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
