# Generated by Django 4.1.2 on 2022-12-01 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0011_alter_fluid_type_name_alter_food_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='report_drink',
            name='phosphorus',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='report_drink',
            name='potassium',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='report_drink',
            name='protein',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='report_drink',
            name='sodium',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='report_drink',
            name='water',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='report_food',
            name='phosphorus',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='report_food',
            name='potassium',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='report_food',
            name='protein',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='report_food',
            name='sodium',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='report_food',
            name='water',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='report_serum',
            name='abumin',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='report_serum',
            name='blood_sugar',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='report_serum',
            name='creatinine',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='report_serum',
            name='phosphorus',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='report_serum',
            name='potassium',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='report_serum',
            name='sodium',
            field=models.FloatField(default=0),
        ),
    ]
