# Generated by Django 4.1.2 on 2022-12-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0012_report_drink_phosphorus_report_drink_potassium_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report_drink',
            name='phosphorus',
        ),
        migrations.RemoveField(
            model_name='report_drink',
            name='potassium',
        ),
        migrations.RemoveField(
            model_name='report_drink',
            name='protein',
        ),
        migrations.RemoveField(
            model_name='report_drink',
            name='sodium',
        ),
        migrations.RemoveField(
            model_name='report_drink',
            name='water',
        ),
        migrations.RemoveField(
            model_name='report_food',
            name='phosphorus',
        ),
        migrations.RemoveField(
            model_name='report_food',
            name='potassium',
        ),
        migrations.RemoveField(
            model_name='report_food',
            name='protein',
        ),
        migrations.RemoveField(
            model_name='report_food',
            name='sodium',
        ),
        migrations.RemoveField(
            model_name='report_food',
            name='water',
        ),
        migrations.AlterField(
            model_name='report_serum',
            name='abumin',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='report_serum',
            name='blood_sugar',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='report_serum',
            name='creatinine',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='report_serum',
            name='phosphorus',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='report_serum',
            name='potassium',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='report_serum',
            name='sodium',
            field=models.FloatField(),
        ),
    ]
