# Generated by Django 4.1.2 on 2022-12-01 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0014_drink_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink_item',
            name='units',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='client_app.drink_units'),
        ),
    ]
