# Generated by Django 4.1.2 on 2022-12-02 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0015_alter_drink_item_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report_drink',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='report_food',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='report_serum',
            name='date',
            field=models.DateField(),
        ),
    ]
