# Generated by Django 4.1.2 on 2022-12-02 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0016_alter_report_drink_date_alter_report_food_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report_food',
            name='phosphorus',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='report_food',
            name='potassium',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='report_food',
            name='protein',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='report_food',
            name='sodium',
            field=models.FloatField(default=0),
        ),
    ]
