# Generated by Django 4.1.2 on 2022-12-02 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0019_food_item_water_report_food_water_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report_drink',
            name='drink',
        ),
        migrations.RemoveField(
            model_name='report_drink',
            name='patient',
        ),
        migrations.DeleteModel(
            name='Drink_Item',
        ),
        migrations.DeleteModel(
            name='Drink_Units',
        ),
        migrations.DeleteModel(
            name='Fluid_Type',
        ),
        migrations.DeleteModel(
            name='Report_Drink',
        ),
    ]
